CREATE DATABASE acm_db;

CREATE TABLE acm_db.Admins (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

INSERT INTO acm_db.Admins VALUES (1, 'admin', '$2a$12$CWUnduTycmnHxaN7EKyFUeaN8N4Ym/Ot9LykTXbRqBPCKGGmSlA/6');

CREATE TABLE acm_db.AbsenceTypes (
    ABSENCE_TYPE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(255) NOT NULL
);

CREATE TABLE acm_db.EmployeeStatus (
    STATUS_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(255)
);

CREATE TABLE acm_db.Employees (
    EMPLOYEE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    STATUS_ID INT,
    FOREIGN KEY (STATUS_ID) REFERENCES acm_db.EmployeeStatus(STATUS_ID)
);

CREATE INDEX Employees_IDX ON acm_db.Employees (EMPLOYEE_ID, STATUS_ID, NAME);

CREATE TABLE acm_db.Absences (
    ABSENCE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_ID INT NOT NULL,
    ABSENCE_TYPE_ID INT NOT NULL,
    DESCRIPTION TEXT,
    HOURS_ABSENT FLOAT NOT NULL,
    ABSENCE_DATE DATE NOT NULL,
    STATUS_ID INT,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES acm_db.Employees(EMPLOYEE_ID),
    FOREIGN KEY (ABSENCE_TYPE_ID) REFERENCES acm_db.AbsenceTypes(ABSENCE_TYPE_ID)
);
